{% set name = "climada" %}
{% set version = "3.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/climada-{{ version }}.tar.gz
  sha256: f625c1785508065307e7a9d51368832f273e00b45c9a863d80997f7345486496

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python =3.9
    - pip
  run:
    - python =3.9
    - bottleneck
    - cartopy
    - cfgrib
    - contextily
    - dask-core
    - deprecation
    - geopandas
    - h5py
    - haversine
    - matplotlib-base
    - netcdf4
    - numba
    - openpyxl
    - overpy
    - pandas
    - pandas-datareader
    - pathos
    - peewee
    - pillow
    - pint
    - pycountry
    - rasterio
    - salib
    - scikit-learn
    - statsmodels
    - sparse
    - pytables
    - tabulate
    - tqdm
    - xarray
    - xlrd
    - xlsxwriter
    - xmlrunner

test:
  imports:
    - climada
    - data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/CLIMADA-project/climada_python
  summary: "CLIMADA: Probabilistic natural catastrophe impact model in Python"
  description: |
    CLIMADA stands for CLIMate ADAptation and is a probabilistic natural catastrophe
    impact model, that also calculates averted damage (benefit) thanks to adaptation
    measures of any kind.
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: https://climada-python.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - peanutfun
